package ru.mephi.prepod.security;

public interface Authority {
    String GET_ATTENDANCE = "GET_ATTENDANCE";
    String EDIT_ATTENDANCE = "EDIT_ATTENDANCE";
    String EDIT_GROUPS = "EDIT_GROUPS";
    String EDIT_BELLS = "EDIT_BELLS";
    String EDIT_INSTITUTES = "EDIT_INSTITUTES";
    String EDIT_LESSONS = "EDIT_LESSONS";
    String EDIT_DEPARTMENTS = "EDIT_DEPARTMENTS";
    String EDIT_LOCATIONS = "EDIT_LOCATIONS";
    String GET_MARKS = "GET_MARKS";
    String EDIT_MARKS = "EDIT_MARKS";
    String EDIT_PHONES = "EDIT_PHONES";
    String EDIT_POSITIONS = "EDIT_POSITIONS";
    String EDIT_PROFESSORS = "EDIT_PROFESSORS";
    String EDIT_STUDENTS = "EDIT_STUDENTS";
    String EDIT_SUBJECTS = "EDIT_SUBJECTS";
    String EDIT_USERS = "EDIT_USERS";

}
