/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.mephi.prepod;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class PrepodApp {
    public static void main(String[] args) {
        SpringApplication.run(PrepodApp.class, args);
    }
}
